services:
  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${__MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${__MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${__MONGODB_DATABASE_NAME}
    ports:
      - '${__MONGODB_PORT}:27017'
    volumes:
      - database:/data/db

volumes:
  database:
