services:
  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${__MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${__MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${__MONGODB_DATABASE_NAME}
    ports:
      - '${__MONGODB_PORT}:27017'
    volumes:
      - database:/data/db

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - '${__MINIO_API_PORT}:9000'
      - '${__MINIO_UI_PORT}:9001'
    volumes:
      - 'minio:/data'
    environment:
      MINIO_ROOT_USER: ${__MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${__MINIO_PASSWORD}
    command: ['server', '/data', '--console-address', ':${__MINIO_UI_PORT}']

  mail:
    image: axllent/mailpit:latest
    restart: unless-stopped
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: '${__MAILPIT_SMTP_USERNAME}:${__MAILPIT_SMTP_PASSWORD}'
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mail:/data
    ports:
      - '${__MAILPIT_SMTP_PORT}:1025'
      - '${__MAILPIT_WEB_UI_PORT}:8025'

volumes:
  database:
  minio:
  mail:
